import type { Category, Finding, ScanResult, Severity } from '../types/index.js';

const SEVERITY_LABEL: Record<Severity, string> = {
  critical: 'CRITICAL',
  error: 'ERROR',
  warn: 'WARN',
  info: 'INFO',
  pass: 'PASS',
};

function cap(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

export function renderMarkdown(result: ScanResult): string {
  const lines: string[] = [];

  lines.push('# OpenClawDoctor+ Scan Report');
  lines.push('');
  lines.push(`- Workspace: \`${result.workspaceRoot}\``);
  lines.push(`- Scanned: ${result.scannedAt}`);
  lines.push(`- Date: ${result.today}`);
  lines.push(`- Overall: **${SEVERITY_LABEL[result.summary.overallSeverity]}**`);
  lines.push(
    `- Checks: ${result.summary.executedChecks} executed, ${result.summary.passedChecks} passed, ${result.summary.skippedChecks} skipped`,
  );
  lines.push('');

  lines.push('## Summary');
  lines.push('');
  lines.push(`OpenClawDoctor+ found **${result.summary.total}** finding(s).`);
  lines.push('');
  for (const sev of ['critical', 'error', 'warn', 'info'] as Severity[]) {
    lines.push(`- ${SEVERITY_LABEL[sev]}: ${result.summary.bySeverity[sev] ?? 0}`);
  }
  lines.push('');

  lines.push('## Findings');
  lines.push('');

  if (result.findings.length === 0) {
    lines.push('No findings. All executed checks passed.');
  } else {
    const groups = new Map<Category, Finding[]>();
    for (const f of result.findings) {
      if (!groups.has(f.category)) groups.set(f.category, []);
      groups.get(f.category)!.push(f);
    }

    for (const [cat, findings] of groups) {
      lines.push(`### ${cap(cat)}`);
      lines.push('');
      for (const f of findings) {
        lines.push(`#### \`${f.checkId}\` ${f.checkName}`);
        lines.push('');
        lines.push(`- Severity: **${SEVERITY_LABEL[f.severity]}**`);
        lines.push(`- Confidence: ${f.confidence}`);
        lines.push(`- Message: ${f.message}`);
        if (f.remediation.length > 0) {
          lines.push('- Remediation:');
          for (const step of f.remediation) {
            lines.push(`  - ${step}`);
          }
        }
        lines.push('');
      }
    }
  }

  if (result.skipped.length > 0) {
    lines.push(`> ${result.skipped.length} check(s) were skipped by the active filters.`);
    lines.push('');
  }

  lines.push('---');
  lines.push('*Generated by OpenClawDoctor+*');
  lines.push('');

  return lines.join('\n');
}
